name: Scrape Committee Schedules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1-5'  # hourly on weekdays; adjust as needed

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Run scraper (default week)
        run: npm run fetch

      # Optional: run with explicit week index (if you know current)
      # - name: Run scraper for week=255
      #   run: WEEK=255 npm run fetch

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update schedules"
            git push
          fi
