name: Fetch Committee Schedules
# GitHub Pages also triggers its managed "pages build and deployment" workflow after this job
# finishes. Seeing two entries in the Actions tab is expected; the second run publishes the
# docs/ artifact to the live site.

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:     # Allow manual triggers

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install chromium

    - name: Run scraper
      run: npm run fetch

    - name: Build published data
      run: npm run build:data

    - name: Build static site
      run: npm run web:build

    - name: Verify generated output
      run: |
        echo "=== Output files ==="
        ls -la output/
        echo ""
        echo "=== House data sample ==="
        head -5 output/house.json 2>/dev/null || echo "house.json missing"
        echo ""
        echo "=== Senate data ==="
        cat output/senate.json 2>/dev/null || echo "senate.json missing"
        echo ""
        echo "=== Debug log tail ==="
        tail -5 output/debug.log 2>/dev/null || echo "debug.log missing"
        echo ""

        echo "=== Published docs/data ==="
        ls -la docs/data/
        echo ""

        echo "=== Published House data sample ==="
        head -5 docs/data/house.json 2>/dev/null || echo "docs/data/house.json missing"
        echo ""

        echo "=== Published Senate data sample ==="
        head -5 docs/data/senate.json 2>/dev/null || echo "docs/data/senate.json missing"
        echo ""

        echo "=== Static site root ==="
        ls -la docs/
        echo ""

        echo "=== Static index preview ==="
        sed -n '1,20p' docs/index.html 2>/dev/null || echo "docs/index.html missing"
        echo ""

        echo "=== Git status ==="
        git status
        echo ""

    - name: Commit scraped data
      run: |
        echo "=== Configuring git ==="
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        echo "=== Adding data files ==="
        git add output/ -v
        if [ -d docs/data ]; then
          git add docs/data/ -v
        else
          echo "docs/data directory not found; skipping staging for site data"
        fi

        if git diff --staged --quiet; then
          echo "✅ No data changes to commit - data is already up to date"
        else
          echo "✅ Committing data updates..."
          git commit -m "Update committee schedules $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload static site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

    - name: Deploy to GitHub Pages
      id: deploy_pages
      uses: actions/deploy-pages@v4

    - name: Upload artifacts (for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-output
        path: output/
