# .github/workflows/scrape.yml
name: Scrape Committee Schedules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1-5'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Remove cache: npm since there's no package-lock.json

      - name: Install dependencies
        run: npm install  # Use npm install instead of npm ci

      - name: Install Playwright browsers
        run: npx playwright-core install chromium


      - name: Run scraper
        run: npm run fetch

      - name: Commit and push updated data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.json output/*.html 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update committee schedules"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
